version: '3'
services:
  database:
    image: mariadb:${DB_VERSION:-10.4}
    volumes:
      - "dbdata:/var/lib/mysql"
      - "./.docker/config/db:/etc/mysql/conf.d"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_DATABASE: ${DB_DATABASE:-wordpress}
      MYSQL_USER: ${DB_USER:-wordpress}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
    restart: always
    command:
      'mysqld --innodb-flush-method=fsync'
  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    restart: always
  php:
    image: devilbox/php-fpm:${PHP_VERSION:-8.0}-work
    depends_on:
      - database
      - redis
    working_dir: /var/www/html
    environment:
      MYSQL_HOST: ${DB_HOST:-database}
      MYSQL_DATABASE: ${DB_DATABASE:-wordpress}
      MYSQL_USER: ${DB_USER:-wordpress}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      WP_CLI_ALLOW_ROOT: true
      NEW_UID: 1000
      NEW_GID: 1000
    volumes:
      - "./.docker/config/php/php.ini:/usr/local/etc/php/conf.d/zzz-php.ini"
      - "./.docker/wordpress:/var/www/html"
    extra_hosts:
      - "${SITE_URL:-general.dev}:host-gateway"
    restart: always
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
  web:
    image: nginx:1-alpine
    depends_on:
      - php
    volumes:
      - "./.docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./.docker/wordpress:/var/www/html"
      - "./.docker/config/certs:/certs:ro"
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "${SITE_URL:-general.dev}:host-gateway"
volumes:
  dbdata: {}
